Repository manpercar1/dp2-G32-Functional-testing, pull requests merged in 2021-05, with the labels that each got.

#31 Spam genérico implementado en Task (update y create) y Shout (create)
  src/main/java/acme/features/administrator/task/AdministratorTaskCreateService.java
  src/main/java/acme/features/administrator/task/AdministratorTaskUpdateService.java
  src/main/java/acme/features/anonymous/shout/AnonymousShoutCreateService.java
  src/main/java/acme/features/manager/task/ManagerTaskCreateService.java
  src/main/java/acme/features/manager/task/ManagerTaskUpdateService.java
  src/main/java/acme/features/spam/SpamShowService.java
Labels: enhancement, fix

#34 Fix errores en AdministratorTaskRepository y ManagerTaskRepository
  src/main/java/acme/features/administrator/task/AdministratorTaskRepository.java
  src/main/java/acme/features/manager/task/ManagerTaskRepository.java
  src/main/webapp/WEB-INF/population/sample-data.xml
Labels: fix

#35 Fix eliminados sysout y añadidas validaciones de spam para author e info
  src/main/java/acme/features/administrator/task/AdministratorTaskCreateService.java
  src/main/java/acme/features/administrator/task/AdministratorTaskUpdateService.java
  src/main/java/acme/features/anonymous/shout/AnonymousShoutCreateService.java
  src/main/java/acme/features/manager/task/ManagerTaskCreateService.java
  src/main/java/acme/features/manager/task/ManagerTaskUpdateService.java
Labels: fix

#53 Tests Authenticated Task
  acme-one.log
  src/main/java/acme/features/authenticated/task/AuthenticatedTaskListService.java
  src/main/java/acme/features/authenticated/task/AuthenticatedTaskListSortedByExecutionPeriodService.java
  src/main/java/acme/features/authenticated/task/AuthenticatedTaskListSortedByWorkloadService.java
  src/main/webapp/WEB-INF/population/initial-data.xml
  src/test/java/acme/testing/authenticated/task/AuthenticatedTaskListAndShowTests.java
  src/test/resources/authenticated/task/list-negative.csv
  src/test/resources/authenticated/task/list-order-execution-period.csv
  src/test/resources/authenticated/task/list.csv
  src/test/resources/authenticated/task/show-negative.csv
Labels: Authenticated

#57 Administrator's tasks' dashboard tests
  src/main/webapp/WEB-INF/population/initial-data.xml
  src/main/webapp/WEB-INF/views/master/i18n_en.messages
  src/test/java/acme/testing/administrator/dashboardTasks/AdministratorDashboardShowServiceTests.java
  src/test/resources/administrator/dashboardTasks/show-negative.csv
  src/test/resources/administrator/dashboardTasks/show-positive.csv
Labels: Administrator

#60 Added some tests
  src/main/webapp/WEB-INF/population/initial-data.xml
  src/test/java/acme/testing/administrator/task/AdministratorTaskUpdateTests.java
  src/test/java/acme/testing/manager/task/ManagerTaskUpdateTests.java
  src/test/resources/administrator/task/update-two-negative.csv
  src/test/resources/manager/task/update-two-negative.csv
Labels: Administrator, Manager

#61 Implementación de los tests de las tareas de un usuario anónimo
  src/main/webapp/WEB-INF/population/sample-data.xml
  src/test/java/acme/testing/AcmeTest.java
  src/test/java/acme/testing/anonymous/task/AnonymousTaskListByExPeriodTest.java
  src/test/java/acme/testing/anonymous/task/AnonymousTaskListTest.java
  src/test/java/acme/testing/anonymous/task/AnonymousTaskShowTest.java
  src/test/java/acme/testing/authenticated/task/AuthenticatedTaskListAndShowTests.java
  src/test/resources/anonymous/task/list.csv
  src/test/resources/anonymous/task/show-negative.csv
  src/test/resources/anonymous/task/show.csv
Labels: Anonymous

#62 Resolución de algunos fallos y actualización
  README.txt
  clevercloud/war.json
  src/main/java/acme/framework/testing/AbstractTest.java
  src/main/webapp/WEB-INF/population/initial-data.xml
  src/test/java/acme/testing/AcmeTest.java
  src/test/java/acme/testing/administrator/dashboardTasks/AdministratorDashboardShowServiceTests.java
  src/test/resources/administrator/dashboardTasks/show-positive.csv
Labels: enhancement, fix

#72 Corrige initial data y sample data
  model.uxf
  src/main/webapp/WEB-INF/population/initial-data.xml
  src/main/webapp/WEB-INF/population/sample-data.xml
Labels: fix

#75 Fix/csv tests
  src/main/java/acme/features/manager/task/ManagerTaskDeleteService.java
  src/test/java/acme/testing/administrator/task/AdministratorTaskDeleteTest.java
  src/test/resources/administrator/task/delete-negative.csv
  src/test/resources/administrator/task/delete.csv
  src/test/resources/administrator/task/list-by-workload-negative.csv
  src/test/resources/administrator/task/list-negative.csv
  src/test/resources/administrator/task/list.csv
  src/test/resources/administrator/task/list_by_execution_period.csv
  src/test/resources/administrator/task/list_by_execution_period_negative.csv
  src/test/resources/administrator/task/show-negative.csv
  src/test/resources/administrator/task/update-two-negative.csv
  src/test/resources/manager/task/delete-negative.csv
  src/test/resources/manager/task/list-by-execution-period-negative.csv
  src/test/resources/manager/task/list-by-workload-negative.csv
  src/test/resources/manager/task/list-negative.csv
  src/test/resources/manager/task/show-negative.csv
  src/test/resources/manager/task/update-two-negative.csv
Labels: fix

#76 SonarLint Analysis and bad smells refactoring
  src/main/java/acme/entities/tasks/Task.java
  src/main/java/acme/entities/tasks/TaskValidator.java
  src/main/java/acme/features/administrator/dashboardTasks/AdministratorDashboardShowService.java
  src/main/java/acme/features/administrator/spam/AdministratorSpamUpdateService.java
  src/main/java/acme/features/administrator/task/AdministratorTaskCreateService.java
  src/main/java/acme/features/administrator/task/AdministratorTaskDeleteService.java
  src/main/java/acme/features/administrator/task/AdministratorTaskListService.java
  src/main/java/acme/features/administrator/task/AdministratorTaskShowService.java
  src/main/java/acme/features/administrator/task/AdministratorTaskUpdateService.java
  src/main/java/acme/features/anonymous/shout/AnonymousShoutCreateService.java
  src/main/java/acme/features/authenticated/task/AuthenticatedTaskListService.java
  src/main/java/acme/features/authenticated/task/AuthenticatedTaskShowService.java
  src/main/java/acme/features/manager/task/ManagerTaskCreateService.java
  src/main/java/acme/features/manager/task/ManagerTaskDeleteService.java
  src/main/java/acme/features/manager/task/ManagerTaskListService.java
  src/main/java/acme/features/manager/task/ManagerTaskShowService.java
  src/main/java/acme/features/manager/task/ManagerTaskUpdateService.java
Labels: bug, fix

#80 Hotfix
  clevercloud/war.json
Labels: fix
